[package]
name = "rustic-local-provider"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]

[dependencies]
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
walkdir = "2.1"
id3 = "0.2"

[dependencies.rustic-core]
git = "https://github.com/rustic-music-player/core"
